### ISSUE TITLE
Wallet client API

### ISSUE THREAD

**Issue by kyranjamie** [stacksgov/sips#117]
There should be a standard describing the style of API used by wallet clients.

@friedger pushed a [draft SIP](https://github.com/stacksgov/sips/pull/59) a while back describing the existing wallet API. Though, more recently, there's been some discussion about moving away from the existing JWT-style API towards something more consistent with other ecosystems, like an RPC style API.

I suggest a SIP that describes a feature-agnostic RPC API that works cross-platform: Web Extensions, mobile apps, CLIs etc, similar to that of [`EIP-1102`](https://eips.ethereum.org/EIPS/eip-1102).

<details>
<summary>SIP Draft</summary>

# Wallet Client API

This SIP describes a simpler standard for apps to interface with wallet clients.

## Abstract

This proposal outlines a uniform manner with which apps can interface with wallet clients.

It recommends to minimise the surface area of available APIs, and makes design decisions similar to those in other crypto ecosystems.

## Introduction

No standard exists describing how apps interact with Stacks-compatible wallets. Presently, ecosystem wallets adhere to an undocumented set of commands that wallets should implement. A well-documented API, that’s familiar to developers from other ecosystems, benefits both app and wallet developers.

The purpose of this SIP is to describe the outline of an API that can support multiple environments including, but not limited to, Web Extensions, mobile wallets, CLIs etc. It does not describe the individual methods that clients may commonly support.

## Specification

Two methods are described. The methods can be typed such that the return value corresponds to the method name passed.

### `request`

`request(method: string, params?: object[]): Promise<T>`

A `request` method is accepted by clients, following the [JSON RPC standard](https://www.jsonrpc.org/specification)

_Example_

```ts
const accounts = await Provider.request('stx_requestAccounts');
```

### `listen`

`listen(event: string): Observable<T>`

A `listen` method accepts an event parameter. It returns an `Observable`, following the [TC39 specification](https://github.com/tc39/proposal-observable), that consumers can subscribe and unsubscribe to.

_Example_

```ts
Provider.listen('networkChange').subscribe(network => toast('Switched network'))
```

## Related Work

[https://eips.ethereum.org/EIPS/eip-1102](https://eips.ethereum.org/EIPS/eip-1102)

[https://eips.ethereum.org/EIPS/eip-1474](https://eips.ethereum.org/EIPS/eip-1474)

[https://eips.ethereum.org/EIPS/eip-2255](https://eips.ethereum.org/EIPS/eip-2255)

## Backwards Compatibility

Wallet clients should continue to support the existing methods until a time where a sufficient majority of apps adhere to the new standard. They may warn developers of the newer format, encouraging developer to migrate.

## Activation

This SIP is considered activated when at least two wallet clients support this API.

</details>

Happy to work on this with anyone that wants to collaborate.

cc/ @janniks @yknl @markmhx @fbwoolf @edu-stx

Edit: March 2023 update

With the suggestions/ideas from this SIP @janniks and I have started http://btckit.org, which aims to push this effort and form a community-driven, wallet-agnostic standard.

**Comment by BhinbahadurUK** [comment]
Packet extract
Name recall
Orders of names sequences forms symbols translation and all translations
open to all languages.


Effectively catch crackers
Identity busters
Rescibing form
Auto executive API to convert from to and to and from
Add binaries
Trunk turning code as reforms re execute.
Payment linked generators to converters
Add payment add-ons to name sourced out by direct linked internlinked
ownership.
Adds from history to and from reform recode run

Quran
Bagavad
All books of research of origin proven.

Recover Payments lost and recover works attaching values of in any.


Hacks denied by redenied entries into list and burn auto

Google all search engine of and in around with complex combined.
Auto deposit
Auto add
Deplenish any claims rewrite software of base code

Always hold ownership owner names and sequence to script and research till
entry nulls as only allowed on world wide Web.

Payments auto find auto pilot auto actual reform auto open



Please




UK Bhinbahadur

**Comment by BhinbahadurUK** [comment]
Good day



Kindly advise as I have received access no only to these communications. Can I have all accounts active note my problems with your banking practices last against me .



I have urgent issues to hand over to FNB as you can search also intermediary work for bridging.

For delay what's my rebate and discounts please
---------- Forwarded message ---------
From: ***@***.******@***.***>>
Date: Fri, 03 May 2019, 12:39
Subject: Your FNB account is ready for use [ REF:9573755 ]
To: ***@***.******@***.***>>


[X]
Thank you for applying for a new FNB Business Account.

Congratulations! All your FICA documentation is in order.

FINAL STEP - Please transfer money into your account to activate it.
You can transfer funds via an EFT, FNB ATM or FNB Branch.

Please note: If you have not yet received your FNB Business Banking Cheque Card, that a courier service will be contacting you shortly to make arrangements for the delivery of your card.

Account number  Branch code     Date opened
62810294009     250655  03/05/2019
Should you need any further assistance with your account, please feel free to contact a Business Banker on 0877 362 247. Operating times: 24/7.

Kind Regards,
FNB Business

[X]



This email is subject to a disclaimer.

Visit the FNB website and view the email disclaimer by clicking the "About FNB + Legal" and "Legal Matters" links.
If you are unable to access our website, please contact us to send you a copy of the email disclaimer.

**Comment by BhinbahadurUK** [comment]
Dear Valued Customer,


Thank you for contacting Jaiz bank plc.

We sincerely regret any inconvenience this might have caused you.

Kindly contact us on 07007730000 to enable us help in resolving the issue.


Thank you for banking with us!




Customer Care


[cid:6736c1be-83aa-45df-a706-4bf588cb5485]

Kano House,

No. 73, Ralph Shodeinde Street,
Central Business District, Abuja

P.M. 31 Garki, Abuja, Nigeria

Mobile: +234 7007730000, +234 7080635555

e-mail: ***@***.***

website: www.jaizbankplc.com<http://www.jaizbankplc.com/>




________________________________
From: Usaman Khallid Bhinbahadur ***@***.***>
Sent: Tuesday, February 7, 2023 11:16 AM
To: ***@***.*** ***@***.***>; Contact Center ***@***.***>; ***@***.*** ***@***.***>; ***@***.*** ***@***.***>; Nedgroup Life Client Services ***@***.***>; ***@***.*** ***@***.***>; ***@***.*** ***@***.***>; stacksgov/sips ***@***.***>
Subject: Fwd: Your FNB account is ready for use [ REF:9573755 ]

Good day



Kindly advise as I have received access no only to these communications. Can I have all accounts active note my problems with your banking practices last against me .



I have urgent issues to hand over to FNB as you can search also intermediary work for bridging.

For delay what's my rebate and discounts please
---------- Forwarded message ---------
From: ***@***.******@***.***>>
Date: Fri, 03 May 2019, 12:39
Subject: Your FNB account is ready for use [ REF:9573755 ]
To: ***@***.******@***.***>>


[X]
Thank you for applying for a new FNB Business Account.

Congratulations! All your FICA documentation is in order.

FINAL STEP - Please transfer money into your account to activate it.
You can transfer funds via an EFT, FNB ATM or FNB Branch.

Please note: If you have not yet received your FNB Business Banking Cheque Card, that a courier service will be contacting you shortly to make arrangements for the delivery of your card.

Account number  Branch code     Date opened
62810294009     250655  03/05/2019
Should you need any further assistance with your account, please feel free to contact a Business Banker on 0877 362 247. Operating times: 24/7.

Kind Regards,
FNB Business

[X]



This email is subject to a disclaimer.

Visit the FNB website and view the email disclaimer by clicking the "About FNB + Legal" and "Legal Matters" links.
If you are unable to access our website, please contact us to send you a copy of the email disclaimer.

**Comment by janniks** [comment]
Leaving my thoughts so far:

1. I like the proposal of adding two simple flexible/generic methods that can be expanded by wallets without needing a SIP for everything. e.g. wallets could prefix beta features (similar to [http headers](https://stackoverflow.com/a/3561399/1139105) or [css rules](https://www.thoughtco.com/css-vendor-prefixes-3466867)) and alias them once a common standard is found/implemented by multiple wallets. 
2. I'm not too sure about the usage of `Observable`. I would prefer describing a native (or more seasoned) JS pattern like a simply `listen(event: string, callback: (error: Error, payload: any) => void)` via callback (which respective connect/client applications could wrap with their favorite `Observable` implementation, but don't have too). Respectively Promises can be used for `async` single requests (eg `get_address`)
3. I like the move away from the cluttered JWT wrapped protocol, in place currently. This simplified API can be used for secure contexts (eg talking to desktop browser extensions), while an additional SIP could target adding sessions (e.g. over relays, similar to wallet-connect, or implementing [wallet-connect](https://docs.walletconnect.com/2.0/javascript/web3wallet/wallet-usage)). Once a secure session is established the session instance could expose the same object as this Wallet API proposal.
4. I'm in favor of short SIPs which can stack on top of each other well (similar to many NIPs [eg](https://github.com/nostr-protocol/nips/blob/master/07.md)) -- so it's nice to see a short and concise SIP which could standardize the parameters of a [`send_transaction`](https://docs.walletconnect.com/1.0/client-api#send-transaction-eth_sendtransaction) request in a follow-up SIP.

Would love to hear @yknl thoughts, especially regarding wallet-connect

**Comment by janniks** [comment]
Wallet Connect docs from Xverse: https://docs.xverse.app/wallet-connect/reference/api_reference

**Comment by whoabuddy** [comment]
FYI - cleaned up some spam comments

**Comment by janniks** [comment]
_Leaving my thought and drafts here for now... Maybe we should use a more collaborative doc for this_ 🤷‍♂

---

## SIP Draft — Wallet Client API

This SIP describes a simpler standard for apps to interface with wallet clients.

### Abstract

This proposal outlines a uniform manner with which apps can interface with wallet clients.

It recommends to minimise the surface area of available APIs, and makes design decisions similar to those in other crypto ecosystems.

### Introduction

No standard exists describing how apps interact with Stacks-compatible wallets. Presently, ecosystem wallets adhere to an undocumented set of commands that wallets should implement. A well-documented API, that’s familiar to developers from other ecosystems, benefits both app and wallet developers.

The purpose of this SIP is to describe the outline of an API that can support multiple environments including, but not limited to, Web Extensions, mobile wallets, CLIs etc. It does not describe the individual methods that clients may commonly support.

### Specification — Wallet Client

A `window.WalletClient` object can be provided by browsers or web extensions so websites/web-apps can check for it's availability and use the provided methods below.

### `request` — _required_

`request(method: string, params?: JSONObject): Promise<T>`

A `request` method is accepted by clients, following the [JSON RPC standard](https://www.jsonrpc.org/specification).

- The `method` parameter describes an action for the wallet to execute.
- The _optional_ `params` parameter offers arbitrary parameters to be passed as a JSON object.

### `listen` — _required_

`listen(event: string, callback: (result) => void): void`

A `listen` method accepts an event parameter.

- The `event` parameter describes a wallet event. On the occurence of an event described by the `event` parameter, the wallet should call the provided callback.
- The `callback` parameter ...

The injected provider should remain lightweight, unopinionated, and use proven JavaScript conventions.
Wrapper libraries (e.g. connect, micro-stacks/client) may choose to wrap the `listen` interface in an `Observable`, following the TC39 specification, that consumers can subscribe and unsubscribe to.

### Examples

`request`

```js
const accounts = await window.WalletClient.request("stacks_requestAccounts");
```

```js
const accounts = await window.WalletClient.request("stacks_sendTransaction", {
  ...
});
```

`listen`

```js
window.WalletClient.listen("networkChange", (network) => {
  alert("Switched network");
});
```

### Notes

**Event/Method Payloads**

This SIP intentionally does not describe what actions/events examples and conventions can be.

**Sessions**

The approach described in this SIP is session-less and assumes a safe/encrypted communication between the wallet and the web-app.

### Comparison

#### Current State

- Safer to have individual RPCs for requesting specific information. E.g. a user might not want to share their mainnet address when sharing a testnet address.
- Better to have a smaller surface area, which doesn't grow stale as the ecosystem evolves (as we have seen in the past with many unused legacy features not needed any more).
- Better suited for multi-chain (e.g. adding BTC transfers)

---

### Todo & Questions

- [ ] `params` always named or allow ordered params (without name)
- [ ] Standardize errors? What does a failure look like, what does an abort/cancel look like? What do missing methods look like?
- [ ] Callback parameter -- Can `listen` have errors?
- [ ] Add getter for retrieving available methods? Dangers? Fingerprinting?
- [ ] JSON RPC `notification`? Or generate `id` (uuid) for each request?
- [ ] JSON RPC response structure? (`error`, `id` etc?)
- [ ] Use MUST SHOULD MAY RFC language?
- [ ] As defined in JSON RPC, the client should set `"jsonrpc": "2.0"` and `"id": new Uuid()` for requests ??
- [ ] Nostr compatible? different namespace? etc.

---

## Sibling SIPs

### #1: [Stacks] Types, Params Interface, Data Type Serialization

It's up to the wallet what to respond to on RPC calls and how to parse data, etc.

But it is prefered to only use named-object params JSONObject.

Some proven defaults are recommended:

**Request Methods**

- `stx_stxTransfer`
- `stx_ftTransfer`
- `stx_nftTransfer`
- `stx_contractCall`
- `stx_contractDeploy`

**Events**

- 'stx_networkChanged'
- 'stx_accountsChanged'

- [ ] `stx_connect`
- [ ] `stx_disconnect`

**Params**

- `recipient` = Stacks address `string`
- `version` = semver `string`; used for versioning the params structure (e.g. a wallet could provide an experimental request method and later use the `version` parameter to deprecate the legacy structure)

Payload independany fields

| field             | type | examples |
| ----------------- | ---- | -------- |
| postConditions    |      |          |
| postConditionMode |      |          |
| nonce             |      |          |
| fee               |      |          |

**Type Serialization/Deserialization**

- Bytes shall be encoded as strings prefixed by `0x`
- BigInts shall be encoded as strings parseable by the `BigInt()` JS constructor.
- `fee`, `from` attributes, which can be inferred or selected from the wallet are _optional_

- [ ] Addresses?
- [ ] `fee`, `nonce` = BigInt

#### WalletConnect

The same params defined for Stacks SIPs should be re-used for adapters like WalletConnect.
This way wallets can share code and provide the same interface directly or via WalletConnect sessions.

### #2: [Bitcoin] Types

### #3: Multi-Chain / Layer -- Client

Provide `Stacks`Client under `window.WalletClient` which can expose multiple layers of bitcoin. This way

```js
window.WalletClient.Stacks ...
                 // ↑
                 // The same as StacksClient, but can group more functionality (e.g. BTC transfers)
```

## Related Work

- https://eips.ethereum.org/EIPS/eip-1102
- https://eips.ethereum.org/EIPS/eip-1474
- https://eips.ethereum.org/EIPS/eip-2255
- https://github.com/nostr-protocol/nips/blob/master/07.md
- https://walletconnect.com
- https://docs.walletconnect.com/2.0/specs/
- https://docs.walletconnect.com/2.0/specs/clients/sign/client-api
- https://docs.walletconnect.com/2.0/javascript/providers/ethereum#events

**Comment by svntax** [comment]
This proposal would help greatly in implementing wallet connecting for game engines with web exports, like Unity and Godot. The current JWT-based API is difficult to work with, so I support this change.

**Comment by markmhx** [comment]
Note that the http://btckit.org/ standard we've started using for Hiro Wallet includes the `.request` approach in this SIP issue from February.

Sats Connect chose not to apply such a `.request` approach when it was released a couple weeks ago despite our hope that it would be adopted among wallets generally, and we don't seem to have heard anything about it from the Xverse team. 

Sats Connect was also promoted as a new API / library, not a standard per se, so it's not clear whether as a library it can incorporate `.request` going forward as well, or whether it proposes an alternative approach for specific reasons. We'd love to hear about them if there's a rationale to going in a different direction.

**Comment by friedger** [comment]
Defined by SIP-030.
Can be closed
